### ISSUE TITLE
Inclusion request review for plibsys/0.0.4@saprykin/stable into conan-center

### ISSUE THREAD

**Issue by danimtb** [saprykin/conan-plibsys#1]
## Inclusion Request Review

This is a review for [plibsys/0.0.4@saprykin/stable (saprykin/public-conan)](https://github.com/saprykin/conan-plibsys) inclusion request to conan-center.
This review follows the [inclusion guidelines of third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
plibsys/0.0.4@saprykin/stable
plibsys/0.0.3@saprykin/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [x] Updated
- [x] Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments

HI @saprykin,

Thank you so much for submiting you library to conan-center. We have reviewed the recipe and the generated packages and here are some things that will require minor improvements:

- We saw you have some tests in CPP but the library you are packaging is pure C, so there is no need to 
  specify `libcxx `in the settings. Your *conanfile.py* should have this:

```
def configure(self):
    del self.settings.compiler.libcxx
```

- There are missing packages for `apple-clang 9.1`. Just add somethig like this to you *.travis.yml* file:
```
      - <<: *osx
        osx_image: xcode9.3
        env: CONAN_APPLE_CLANG_VERSIONS=9.1
```

- Finally we saw you are using the Bincrafters template for this repo. Are you planning to move it to the bincrafters organization? I so, it would be better to wait until it is moved to do the inclusion into conan-center

**Comment by solvingj** [comment]
Might as well also add GCC8 at this point:

```
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=lasote/conangcc8 CONAN_ARCHS=x86 CONAN_DOCKER_32_IMAGES=1
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=lasote/conangcc8 CONAN_ARCHS=x86_64
```

**Comment by saprykin** [comment]
Hi @danimtb,
I've added CXX to project settings and Xcode 9.3 builds. I use bincrafters template because initially @solvingj made a port to conan in bincrafters, then I started to transfer and improve the port in my own repo. What people do usually put for conan repo of their project? If you can link me some examples, I can make something similar (i.e. if you have any templates or guidelines).

Hi @solvingj,
Done with GCC8.

**Comment by danimtb** [comment]
Hello @saprykin and sorry for the delay. It seems some Linux packages were uploaded with a wrong format to the server. We have been tracking the issue and seems solved.

Would you mind triggering Travis CI manually again?

Thanks a lot!

**Comment by saprykin** [comment]
Hi @danimtb,

I've restarted it, seems to be finished successfully.

**Comment by danimtb** [comment]
Great thanks!

I have already included it in conan-center. Please there are some outdated packages (yellow) that were left due to the removal of libcxx (as this is a pure C library):

`conan search plibsys/0.0.4@saprykin/stable -r saprykin_remote --table=table.html`
![image](https://user-images.githubusercontent.com/10808592/42813229-8a765160-89c0-11e8-9008-77a19b3cadbc.png)

Please remove them when possible using: `conan remove plibsys/0.0.4@saprykin/stable -r saprykin_remote --outdated`

Thanks a lot @saprykin and @solvingj for including this into conan-center! 😄

**Comment by solvingj** [comment]
https://twitter.com/conan_io/status/1019336366172274688

**Comment by saprykin** [comment]
Thanks @danimtb to pushing it! I will clean the build this week. Thanks @solvingj for the promo :)
